name: build
on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest ]
        bazel: [ "4.2.1", "5.0.0-pre.20210929.1" ]
        java: [ 11, 17 ]
    runs-on: ${{ matrix.os }}
    name: OS ${{ matrix.os }} bazel ${{ matrix.bazel }} java ${{ matrix.java }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Set Bazelisk Version ${{ matrix.bazel }}
        run: |
          echo ${{ matrix.bazel }} > .bazelversion
      - name: Build
        run: |
          ./baseliskw build //...
